system:
  # List of available punishment systems can be found here:
  # https://docs.xemu.codes/disablesignswhilemuted-wiki/supported-systems
  # If you do not have the system installed it wont work properly.
  active: "" # Write in the system name (CASE SENSITIVE)
message: "&cYou are muted, and you cannot use signs now."
message-staff:
  enabled: false
  message: "&c<target> attempted to use a sign, but cannot because they are muted."

disable-book-edit: true

# Important Changelog:
# [11-October-2022] Disable Signs While Muted was renamed to NoMuteBypass.
