name: NoMuteBypass
version: '${project.version}'
main: io.github.codebyxemu.nomutebypass.NoMuteBypass
api-version: 1.19
description: Disable signs for muted players.

softdepend:
  - AdvancedBan
  - LiteBans
  - Essentials
  - UltraPunishments
  - LibertyBans
  - AquaCore

commands:
  dswm:
    description: Main Command
    aliases: [disablesignswhilemuted, disablesignwhilemuted]